server:
  port: 9005
spring:
  application:
    name: springcloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahxingczx/microservice.git
          search-paths: /src/main/resources/config
          #token: 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
          #0604  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
          username: ahxingczx
          password: Czx136504

